In [ ]:
# Matrix Inversion

Matrix inversion is the process of finding a matrix $A^{-1}$ such that
\begin{equation} 
A^{-1} A = \mathbb{1}, 
\end{equation}

where $\mathbb{1}$ is the identity matrix (a matrix of all zeros except with ones along the diagonal). 

Consider 
\begin{equation} 
A = \begin{bmatrix}
4 & 7 \\
2 & 6
\end{bmatrix}.
\end{equation} 

The inverse of $A$ is 
\begin{equation} 
A^{-1}=
 \begin{bmatrix}
0.6 & -0.7 \\
-0.2 & 0.4
\end{bmatrix},
\end{equation}

such that 

\begin{equation} 
\begin{bmatrix}
4 & 7 \\
2 & 6
\end{bmatrix}
 \begin{bmatrix}
0.6 & -0.7 \\
-0.2 & 0.4
\end{bmatrix} =  \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
\end{equation} 
Let us check this in Python using the np.linalg.inv function. Here is the code. 

In [2]:
import numpy as np

# Define a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Inverse of A:")
print(A_inv)

print("Check that multiplication gives the identitiy.") 
print(A@A_inv)

Inverse of A:
[[ 0.6 -0.7]
 [-0.2  0.4]]
Check that multiplication gives the identitiy.
[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]


The code output is as expected. Note that the off-diagonal elements above are not exactly zero. This is due to round-off error. More on round-off error in a future lesson. Let us check a larger matrix. To do so, we will make use of the `np.random.rand` function to generate a matrix composed of random numbers from 0 to 1.

In [3]:
A=np.random.rand(5,5)

A_inv=np.linalg.inv(A)

A_inv@A

array([[ 1.00000000e+00,  1.53949667e-16, -1.48038412e-16,
        -5.22462990e-17,  1.61269675e-18],
       [-1.87301136e-16,  1.00000000e+00, -2.17598336e-16,
        -5.12401436e-16, -2.43541291e-16],
       [ 1.89100791e-16,  2.44896342e-17,  1.00000000e+00,
        -6.44636527e-17, -1.44117895e-16],
       [ 2.48363052e-16,  1.23845726e-15,  5.21290389e-16,
         1.00000000e+00,  7.58552031e-16],
       [-5.71229063e-16, -8.91369251e-16, -4.72555184e-16,
        -3.33562176e-16,  1.00000000e+00]])

Yes, the output is a bit messy. But if you inspect it, you will see that it is the identity matrix up to round off error. 

## Solving Systems of Equations 
Matrix inversion appears equations of the form
\begin{equation} 
A \cdot \mathbf{x} = \mathbf{b}~,
\end{equation} 
where $A$ and $\mathbf{b}$ are a known matrix and vector and $\mathbf{x}$ is unknown. 

The solution can be solved by multiplying both side by $A^{-1}$
\begin{equation} 
\begin{split} 
& A^{-1} A \cdot \mathbf{x} = A^{-1}\mathbf{b} \\
&  \mathbf{x}= A^{-1}\mathbf{b}.
\end{split} 
\end{equation} 

A typical use case is solving systems of equations. For example consider the following
\begin{equation} 
\begin{aligned}
4x_0 + 7x_1 &= 1 \\
2x_0 + 6x_1 &= 3.
\end{aligned}
\end{equation} 

This can be written as 

\begin{equation} 
A = \begin{bmatrix}
4 & 7 \\
2 & 6
\end{bmatrix}, \quad
\mathbf{x} = \begin{bmatrix}
x_0 \\
x_1
\end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix}
1 \\
3
\end{bmatrix}.
\end{equation} 

We can solve this system in two ways with Python. 
1) Using the np.linalg.inv function.
2) Using the np.linalg.solve function.

Here is code for both methods. 

In [4]:
A = np.array([[4, 7], [2, 6]]) 
b = np.array([1, 3]) 

In [5]:
# method 1 
A_inv=np.linalg.inv(A) 
x = A_inv@b
print(x) 

[-1.5  1. ]


In [6]:
# method 2 
x=np.linalg.solve(A, b) 
print(x) 

[-1.5  1. ]


The two methods are equivalent. **But it is wise not to directly invert matrices as in method 1 and instead use methods similar to method 2.** This topic will be discussed in more detail in latter lectures. 

## Should You Directly Invert a Matrix in Numerical Methods? (Hint: almost always No)

The short answer is: **No, you should generally avoid directly inverting a matrix when solving systems of equations.**


In numerical computing, using `np.linalg.inv(A)` and then multiplying with `b` like `x = A⁻¹b` can lead to problems:

| Problem                  | Why it's bad                                                                 |
|--------------------------|------------------------------------------------------------------------------|
| **Numerically unstable** | Floating-point errors can result in inaccurate solutions                    |
| **Computationally costly** | Inverting an $n \times n$ matrix takes ~\(O(n^3)\) operations           |
| **Unnecessary**          | You almost never need the explicit inverse to solve a system                |

---


Instead of this:

```python
# Not recommended
x = np.linalg.inv(A) @ b
```
Do this:
```
# Recommended
x = np.linalg.solve(A, b)
```
Before moving on, I must say that studing matrix methods will be a major componet of this course. Be sure are familiar with basics outlines in these notebooks. Don't forget, that in most cases, it is best not to directly invert a matrix. 

## Inversion for $3\times3$ Matrices 
Here I will present code to invert a $3\times 3$ matrix using the determinate and the adjugate. This is not the type of coding you would expect to do when doing real scientific computing, but it still helps the student gain familiarity with indexing and array manipulations. 

Let $A$ be a $3 \times 3$ matrix given by:
\begin{equation}
A = \begin{pmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{pmatrix}
\end{equation}
The inverse of $A$, denoted by $A^{-1}$, is given by:
\begin{equation}
A^{-1} = \frac{1}{\det(A)} \text{adj}(A)
\end{equation}
where $\det(A)$ is the determinant of $A$ and $\text{adj}(A)$ is the adjugate of $A$.

**Step 1: Calculate the Determinant of A ($\det(A)$)**
The determinant of a $3 \times 3$ matrix is calculated as:
\begin{equation}
\det(A) = a(ei - fh) - b(di - fg) + c(dh - eg)
\end{equation}
If $\det(A) = 0$, the matrix $A$ is singular and has no inverse.

**Step 2: Find the Matrix of Minors ($M$)**
The matrix of minors $M$ is formed by taking the determinant of the $2 \times 2$ submatrix obtained by removing the $i$-th row and $j$-th column for each element of $A$:
\begin{equation}
M = \begin{pmatrix}
\begin{vmatrix} e & f \\ h & i \end{vmatrix} & \begin{vmatrix} d & f \\ g & i \end{vmatrix} & \begin{vmatrix} d & e \\ g & h \end{vmatrix} \\
\begin{vmatrix} b & c \\ h & i \end{vmatrix} & \begin{vmatrix} a & c \\ g & i \end{vmatrix} & \begin{vmatrix} a & b \\ g & h \end{vmatrix} \\
\begin{vmatrix} b & c \\ e & f \end{vmatrix} & \begin{vmatrix} a & c \\ d & f \end{vmatrix} & \begin{vmatrix} a & b \\ d & e \end{vmatrix}
\end{pmatrix}
= \begin{pmatrix}
(ei - fh) & (di - fg) & (dh - eg) \\
(bi - ch) & (ai - cg) & (ah - bg) \\
(bf - ce) & (af - cd) & (ae - bd)
\end{pmatrix}
\end{equation}

**Step 3: Find the Matrix of Cofactors ($C$)**
The matrix of cofactors $C$ is obtained by applying a checkerboard pattern of signs to the matrix of minors $M$:
\begin{equation}
C = \begin{pmatrix}
+ & - & + \\
- & + & - \\
+ & - & +
\end{pmatrix} \odot M = \begin{pmatrix}
+(ei - fh) & -(di - fg) & +(dh - eg) \\
-(bi - ch) & +(ai - cg) & -(ah - bg) \\
+(bf - ce) & -(af - cd) & +(ae - bd)
\end{pmatrix}
\end{equation}
where $\odot$ denotes the element-wise product.

**Step 4: Find the Adjugate (Adjoint) of A ($\text{adj}(A)$)**
The adjugate of $A$ is the transpose of the cofactor matrix $C$:
\begin{equation}
\text{adj}(A) = C^T = \begin{pmatrix}
+(ei - fh) & -(bi - ch) & +(bf - ce) \\
-(di - fg) & +(ai - cg) & -(af - cd) \\
+(dh - eg) & -(ah - bg) & +(ae - bd)
\end{pmatrix}
\end{equation}

**Step 5: Calculate the Inverse $A^{-1}$**
Finally, the inverse of $A$ is obtained by multiplying the adjugate of $A$ by $\frac{1}{\det(A)}$:
\begin{equation}
A^{-1} = \frac{1}{a(ei - fh) - b(di - fg) + c(dh - eg)} \begin{pmatrix}
(ei - fh) & -(bi - ch) & (bf - ce) \\
-(di - fg) & (ai - cg) & -(af - cd) \\
(dh - eg) & -(ah - bg) & +(ae - bd)
\end{pmatrix}
\end{equation}


In [7]:
def determinant_3x3(matrix):
    """
    Computes the determinant of a 3x3 NumPy matrix.

    Args:
        matrix (numpy.ndarray): A 3x3 NumPy matrix.

    Returns:
        float: The determinant of the input matrix.
               Returns None if the input is not a 3x3 matrix.
    """
    if matrix.shape != (3, 3):
        print("Error: Input matrix must be 3x3.")
        return None

    return (matrix[0, 0] * (matrix[1, 1] * matrix[2, 2] - matrix[1, 2] * matrix[2, 1]) -
            matrix[0, 1] * (matrix[1, 0] * matrix[2, 2] - matrix[1, 2] * matrix[2, 0]) +
            matrix[0, 2] * (matrix[1, 0] * matrix[2, 1] - matrix[1, 1] * matrix[2, 0]))



def adjugate_3x3(matrix):
    """
    Computes the adjugate (adjoint) of a 3x3 NumPy matrix.

    Args:
        matrix (numpy.ndarray): A 3x3 NumPy matrix.

    Returns:
        numpy.ndarray: The adjugate of the input matrix.
                       Returns None if the input is not a 3x3 matrix.
    """
    if matrix.shape != (3, 3):
        print("Error: Input matrix must be 3x3.")
        return None

    # Calculate the matrix of minors
    minors = np.zeros((3, 3))
    for i in range(3):
        for j in range(3):
            submatrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            minors[i, j] = np.linalg.det(submatrix)

    # Calculate the matrix of cofactors
    cofactors = np.zeros((3, 3))
    for i in range(3):
        for j in range(3):
            cofactors[i, j] = minors[i, j] * ((-1)**(i + j))

    # The adjugate is the transpose of the cofactor matrix
    adjugate = cofactors.T

    return adjugate


In [10]:
# test 
C=np.random.rand(3,3)
detC=determinant_3x3(C)

adj=adjugate_3x3(C)

C_inv=1/detC*adj
print("Inverse of C", C_inv)
print("Check that C^{-1}C, results in identity matrix", C_inv@C)

Inverse of C [[-1.17486087 -0.16137173  1.6761027 ]
 [ 4.05557936 -0.66435367 -1.75181125]
 [-2.53685815  2.28987035  0.21015831]]
Check that C^{-1}C, results in identity matrix [[ 1.00000000e+00  2.02654949e-17  3.44681172e-17]
 [ 1.39801789e-16  1.00000000e+00 -9.11448096e-18]
 [ 3.47577730e-16  3.09275515e-16  1.00000000e+00]]
