# Guassian Elimination 

In [1]:
import numpy as np


In [2]:
def forward_sub(L,b):
    
    n=b.size
    x=np.zeros(n)
    
    for i in range(n):
        x[i] = (b[i] - np.dot(L[i,:i],x[i+1:]))/L[i,i]
                
    return x

def backward_sub(U,b):
    
    n=b.size
    x=np.zeros(n) 
    
    x[n-1]=b[n-1]/U[n-1, n-1]
    
    for i in reversed(range(n-1)):
        
        x[i] = (b[i] - np.dot(U[i, i+1:],x[i+1:]))/U[i,i]
                
    return x

def gauss_elim(A_in, b_in):
    
    A=np.copy(A_in)
    b=np.copy(b_in) 
    
    n=b.size
    
    for j in range(n-1):
        for i in range(j+1,n):
            
            coef=A[i,j]/A[j,j]
            
            A[i,j:] -= coef*A[j,j:]
            b[i]-=coef*b[j] 
     
    print(A)
    print("b",b)
    return backward_sub(A,b)


A=np.random.uniform(0,10,size=(3,3))
x=np.random.uniform(0,10,size=3)
b=np.dot(A,x) 

print(b) 
print("x true", x)
print("x solved", gauss_elim(A,b))

[99.11013552 70.37976279 74.48772245]
x true [3.89805876 3.06399721 5.59118079]
[[ 8.14375924  7.04777175  8.18627266]
 [ 0.          5.67390097 -0.29013897]
 [ 0.          0.          0.93047105]]
b [99.11013552 15.76259726  5.20243189]
x solved [3.89805876 3.06399721 5.59118079]


In [9]:
np.dot(L,U)

array([[7.86454061, 1.71195438, 8.14099258],
       [7.17292289, 9.58143421, 1.4584728 ],
       [9.30466821, 8.10308685, 0.79493191]])

In [10]:
A

array([[7.86454061, 1.71195438, 8.14099258],
       [7.17292289, 9.58143421, 1.4584728 ],
       [9.30466821, 8.10308685, 0.79493191]])