# Matrix Transpose 

The transpose of a matrix is an operation that interchanges the rows and columns of a matrix;  the element at the $i$-th row and $j$-th column of the original matrix becomes the element at the $j$-th row and $i$-th column in the transposed matrix. The transpose of matrix $A$ is denoted as $A^T$. Here is an example. 

\begin{equation} 
A = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}, \quad
A^T = \begin{bmatrix}
a & d & g \\
b & e & h \\
c & f & i
\end{bmatrix}
\end{equation} 

In index notation, matrix transpose is
\begin{equation} 
A^{T}_{ij} = A_{ji}  
\end{equation} 

In NumPy you can obtain the transpose with the following commands: 
* array.T
* np.transpose(array)

Here are some examples in NumPy and Jax. 

In [33]:
import numpy as np
import sympy as sym
import jax.numpy as jnp 
import jax  

In [3]:
# example matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [4]:
# transpose with .T
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [5]:
# tranpose with np.transpose
np.transpose(matrix) 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Here is an example using NumPy's random package to generate a non-square matrix of random integers. 

In [9]:
# use NumPy's random package to generate a matrix composed of random integers
M = np.random.randint(-10,10,size=(2,3))
print(M)
print(M.shape) 

[[-8  5  1]
 [-7 -4 -2]]
(2, 3)


In [10]:
M.T

array([[-8, -7],
       [ 5, -4],
       [ 1, -2]])

In [11]:
np.transpose(M) 

array([[-8, -7],
       [ 5, -4],
       [ 1, -2]])

Here is an example using Jax. Jax's random number generator works a bit differently than NumPy. See the Jax documentation: 
* [PRNGKey](https://docs.jax.dev/en/latest/_autosummary/jax.random.PRNGKey.html)
* [randomint](https://docs.jax.dev/en/latest/_autosummary/jax.random.PRNGKey.html)

In [28]:
seed=43
key =jax.random.PRNGKey(seed)
M=jax.random.randint(minval=-100,maxval=100, key=key, shape=(4,2))
M

Array([[-44, -73],
       [ 87, -33],
       [-93,  69],
       [ 88, -26]], dtype=int32)

In [29]:
# transpose with T
M.T

Array([[-44,  87, -93,  88],
       [-73, -33,  69, -26]], dtype=int32)

In [30]:
# transpose with jnp.transpose
jnp.transpose(M) 

Array([[-44,  87, -93,  88],
       [-73, -33,  69, -26]], dtype=int32)

Here are some examples using SymPy. 
**Note: SymPy uses * for matrix multiplication. * in NumPy is used for element-wise multiplication.**

In [35]:
a_11, a_12, a_13, a_21, a_22, a_23, a_31, a_32, a_33 = \
sym.symbols("a_11 a_12 a_13 a_21 a_22 a_23 a_31 a_32 a_33") 

A = sym.Matrix([[a_11, a_12, a_13],[a_21, a_22, a_23], [a_31, a_32, a_33]]) 
A

Matrix([
[a_11, a_12, a_13],
[a_21, a_22, a_23],
[a_31, a_32, a_33]])

In [37]:
# using the .T command 
A.T

Matrix([
[a_11, a_21, a_31],
[a_12, a_22, a_32],
[a_13, a_23, a_33]])

## Properties of Transpose
1. **Double Transpose**: The transpose of the transpose of a matrix returns the original matrix: $(A^T)^T = A $.

2. **Addition**: The transpose of the sum of two matrices equals the sum of their transposes: $(A + B)^T = A^T + B^T $.

   
3. **Scalar Multiplication**: Transposing a scalar multiplied by a matrix results in the scalar multiplied by the transposed matrix: $(cA)^T = cA^T $, where $c$ is a scalar.

   
4. **Matrix Multiplication**: The transpose of the product of two matrices is equal to the product of their transposes in reverse order: $(AB)^T = B^T A^T$.

Here are examples of each of the properties above in Python. 

NumPy example of double transpose (transpose of the transpose). 

In [72]:
A = np.random.randint(-4,4, size=(3,3))
A

array([[-2,  1,  1],
       [ 0, -1,  2],
       [ 3,  1,  0]])

In [73]:
# tranpose of the transpose
A.T.T

array([[-2,  1,  1],
       [ 0, -1,  2],
       [ 3,  1,  0]])

SymPy example of the addition property.

In [74]:
a_11, a_12, a_13, a_21, a_22, a_23, a_31, a_32, a_33 = \
sym.symbols("a_11 a_12 a_13 a_21 a_22 a_23 a_31 a_32 a_33") 

A = sym.Matrix([[a_11, a_12, a_13],[a_21, a_22, a_23], [a_31, a_32, a_33]]) 


b_11, b_12, b_13, b_21, b_22, b_23, b_31, b_32, b_33 = \
sym.symbols("b_11 b_12 b_13 b_21 b_22 b_23 b_31 b_32 b_33") 

B = sym.Matrix([[b_11, b_12, b_13],[b_21, b_22, b_23], [b_31, b_32, b_33]]) 

In [75]:
C = A + B 
C 

Matrix([
[a_11 + b_11, a_12 + b_12, a_13 + b_13],
[a_21 + b_21, a_22 + b_22, a_23 + b_23],
[a_31 + b_31, a_32 + b_32, a_33 + b_33]])

In [76]:
C.T

Matrix([
[a_11 + b_11, a_21 + b_21, a_31 + b_31],
[a_12 + b_12, a_22 + b_22, a_32 + b_32],
[a_13 + b_13, a_23 + b_23, a_33 + b_33]])

In [77]:
D = A.T + B.T
D 

Matrix([
[a_11 + b_11, a_21 + b_21, a_31 + b_31],
[a_12 + b_12, a_22 + b_22, a_32 + b_32],
[a_13 + b_13, a_23 + b_23, a_33 + b_33]])

In [78]:
C.T == D 

True

SymPy example of transpose of product, $(AB)^T = B^T A^T$.

In [79]:
C = A*B 
C.T

Matrix([
[a_11*b_11 + a_12*b_21 + a_13*b_31, a_21*b_11 + a_22*b_21 + a_23*b_31, a_31*b_11 + a_32*b_21 + a_33*b_31],
[a_11*b_12 + a_12*b_22 + a_13*b_32, a_21*b_12 + a_22*b_22 + a_23*b_32, a_31*b_12 + a_32*b_22 + a_33*b_32],
[a_11*b_13 + a_12*b_23 + a_13*b_33, a_21*b_13 + a_22*b_23 + a_23*b_33, a_31*b_13 + a_32*b_23 + a_33*b_33]])

In [80]:
B.T*A.T

Matrix([
[a_11*b_11 + a_12*b_21 + a_13*b_31, a_21*b_11 + a_22*b_21 + a_23*b_31, a_31*b_11 + a_32*b_21 + a_33*b_31],
[a_11*b_12 + a_12*b_22 + a_13*b_32, a_21*b_12 + a_22*b_22 + a_23*b_32, a_31*b_12 + a_32*b_22 + a_33*b_32],
[a_11*b_13 + a_12*b_23 + a_13*b_33, a_21*b_13 + a_22*b_23 + a_23*b_33, a_31*b_13 + a_32*b_23 + a_33*b_33]])

In [67]:
B.T*A.T == C.T

True

SymPy example of transpose of product, $(A\mathbf{x})^T = \mathbf{x}^T A^T$, where $\mathbf{x}$ is a vector. 

In [68]:
x_1 , x_2, x_3 = sym.symbols("x_1 x_2 x_3") 

x=sym.Matrix([x_1, x_2, x_3]) 

z= A*x
z

Matrix([
[a_11*x_1 + a_12*x_2 + a_13*x_3],
[a_21*x_1 + a_22*x_2 + a_23*x_3],
[a_31*x_1 + a_32*x_2 + a_33*x_3]])

In [69]:
z.T

Matrix([[a_11*x_1 + a_12*x_2 + a_13*x_3, a_21*x_1 + a_22*x_2 + a_23*x_3, a_31*x_1 + a_32*x_2 + a_33*x_3]])

In [70]:
u=x.T*A.T
u

Matrix([[a_11*x_1 + a_12*x_2 + a_13*x_3, a_21*x_1 + a_22*x_2 + a_23*x_3, a_31*x_1 + a_32*x_2 + a_33*x_3]])

In [71]:
z.T==u

True