# Matrix Condition Number
## draft version do not distribute 

In [55]:
%%html 
<div align="center">
<iframe width="600" height="400" <iframe width="560" height="315" src="https://www.youtube.com/embed/Axdj-m4bjyw?si=B_VQllegJXDVVkA3" </iframe>


## References: 
* [What is a the Condition Number of a Matrix?, Cleve Moler](https://blogs.mathworks.com/cleve/2017/07/17/what-is-the-condition-number-of-a-matrix/)
* [Numerical Methods in Physics with Python, Alex Gexerlis](https://numphyspy.org/)

A condition number measures how sensitive a function's output is to changes or errors in its input. In these notes, we focus on linear systems of equations, which are problems of the form:

\begin{equation}
A \mathbf{x} = \mathbf{b}.
\end{equation}

The question we will address is how the solution to equations of the form $A\mathbf{x} = \mathbf{b}$ changes if we introduce small perturbations to the elements of $A$ or $\mathbf{b}$. The **matrix condition number** quantifies the impact these small changes have on the solution.

Now, consider changing the elements of matrix $A$ slightly—how much does this affect the solution, $\mathbf{x}$? In a word-schematic equation, we can express this relationship as:

\begin{equation}
\text{changes in } \mathbf{x} \leq \text{some number} \times \text{small changes in } A.
\end{equation}

The matrix condition number is this "some number." If the number is small, then small changes in $A$ map to small changes in $\mathbf{x}$. However, if the number is large, small changes in $A$ may have a significant impact on the solution $\mathbf{x}$.

Likewise, the condition number specifies how small changes in $\mathbf{b}$ propagte to changes in $\mathbf{x}$. 

----

## Matrix Norms
We will utilize the properties of [matrix norms](https://en.wikipedia.org/wiki/Matrix_norm). Below are the key properties of matrix norms:

- $|| A || > 0$
- $|| A || = 0$ if and only if all elements are zero, i.e., $A_{ij} = 0$ for all $i$, $j$
- $|| k A || = |k| || A ||$, where $k$ is a scalar
- $|| A + B || \leq || A || + || B ||$, known as the triangle inequality
- $|| A B || \leq || A || || B ||$

If you're wondering what a norm is, a common one is the Euclidean norm (also known as the $l^2$ norm or "el-2"), which is the square root of the sum of all elements squared:

\begin{equation}
|| A ||_2 = \sqrt{ \sum_i \sum_j A_{ij}^2}.
\end{equation}

You can check this in Python with the following code. 
```python
A = np.random.rand(3,3)
print(np.linalg.norm(A))
norm=0
for i in range(3):
    for j in range(3): 
        norm += A[i,j]**2
print(np.sqrt(norm))
```

----
## Condition Number 
We will now derive the condition number. Keep in mind that there are multiple ways to derive the condition number, and the approach we are using is just one of them.

We perturb the matrix $A$ by adding a small change, $\Delta A$, so that $A \to A + \Delta A$. As a result, we expect the output $\mathbf{x}$ to change under this perturbation. We should think of this as how the error introduced by adding $\Delta A$ to $A$ maps to an error in the solution, i.e., how $\mathbf{x}$ changes to $\mathbf{x} + \Delta \mathbf{x}$.

Adding perturbations to the equation $A \mathbf{x} = \mathbf{b}$, we have:

\begin{equation}
\begin{split} 
(A + \Delta A) ( \mathbf{x} + \Delta \mathbf{x}) & = \mathbf{b} \\
A \mathbf{x}  + \Delta A\mathbf{x} + A  \Delta \mathbf{x} + \Delta A \Delta \mathbf{x} & = \mathbf{b}.
\end{split} 
\end{equation} 
The first term on the left hand side and the right hand side are equal, since $A \mathbf{x} = \mathbf{b}$. Continuing we have
\begin{equation} 
\begin{split} 
 A  \Delta \mathbf{x} &  = - \Delta A\mathbf{x} -  \Delta A \Delta \mathbf{x} \\
A  \Delta \mathbf{x} &  = - \Delta A ( \mathbf{x} +  \Delta \mathbf{x}) \\
\Delta \mathbf{x} & = -A^{-1} \Delta A ( \mathbf{x} +  \Delta \mathbf{x}). 
\end{split} 
\end{equation} 
We now take the norm of both sides. 
\begin{equation} 
\begin{split} 
& ||\Delta \mathbf{x} || = ||A^{-1} \Delta A ( \mathbf{x} +  \Delta \mathbf{x}) || \\
& ||\Delta \mathbf{x} || \leq ||A^{-1} || ~||\Delta A ||~||( \mathbf{x} +  \Delta \mathbf{x}) || \\
& ||\Delta \mathbf{x} || \leq ||A^{-1} || ~||\Delta A ||~|| \mathbf{x}||
\end{split} 
\end{equation} 
Note, in the second line the norm property, $|| A +  B|| \leq || A|| + ||B||$ was used. Continuing we have
\begin{equation} 
\begin{split} 
& \frac{ || \Delta \mathbf{x} ||}{|| \mathbf{x} ||} \leq ||A^{-1} || ~||\Delta A || \frac{ || A ||}{||A||}  \\
& \frac{ || \Delta \mathbf{x} ||}{|| \mathbf{x} ||} \leq ||A^{-1} || ~|| A|| \frac{ ||\Delta A ||}{||A||}\\
& \frac{ || \Delta \mathbf{x} ||}{|| \mathbf{x} ||} \leq \kappa(A) \frac{ ||\Delta A ||}{||A||}, 
\end{split} 
\end{equation} 
where $\kappa(A) = ||A^{-1} || ~|| A||$ is the condition number. 
If the condition number is large, then even small perturbations in $A$ can lead to a large error in $\frac{ || \Delta \mathbf{x} ||}{|| \mathbf{x} ||}$. 

Likewise, the condition number sets a bound on how small changes in $\mathbf{b}$ propagate to changes in $\mathbf{x}$: \begin{equation} \frac{||\Delta \mathbf{x}||}{||\mathbf{x}||} \leq \kappa(A) \frac{||\Delta \mathbf{b}||}{||\mathbf{b}||}. \end{equation} This inequality shows that the relative change in the solution $\mathbf{x}$ is at most $\kappa(A)$ times the relative change in $\mathbf{b}$.



## What is a Large Condition Number
- condition numbers on the order of 1 are excellent 
- condition numbers on the order of $10$ to $10^2$ are considered "well-conditioned"
- condition numbers larger than $10^2$ are "ill-conditioned"

## How to get the Condition Number
Numpy provides a function for the condition number, np.linalg.cond(). 

----

## Here are Some Examples

In [56]:
import numpy as np
from scipy.linalg import hilbert

### Example From Video 
\begin{equation} 
A = \begin{bmatrix} 0.2161 & 0.1441 \\
1.2969 & 0.8648 \end{bmatrix} 
\end{equation} 

\begin{equation} 
\mathbf{b} = \begin{bmatrix} 0.1440 \\ 0.8642 \end{bmatrix} 
\end{equation} 

### Exercise
Find the solution $\mathbf{x}$ to $A \mathbf{x}= \mathbf{b}$ for the above example. Use NumPy to get the condition number of $A$. Perturb \mathbf{b} and observe how the output changes.

In [57]:
A = np.array([[0.2161, 0.1441],[1.2969, 0.8648]]) 
b = np.array([0.1440, 0.8642]) 

In [58]:
A 

array([[0.2161, 0.1441],
       [1.2969, 0.8648]])

In [59]:
b

array([0.144 , 0.8642])

In [60]:
# A has a very large condition number 
kappa=np.linalg.cond(A) 
kappa

249729263.7996639

In [61]:
# solve for x 
x = np.linalg.solve(A, b) 
x 

array([ 2., -2.])

In [62]:
# check solution 
A@x

array([0.144 , 0.8642])

In [63]:
# add perturbation to b 
db = np.array([0, .00001]) 

bp = b + db
bp 

array([0.144  , 0.86421])

In [64]:
# see how perturbation changes output 
xp = np.linalg.solve(A, bp) 
xp 

array([ 146.10000023, -218.10000034])

### Hilbert Matrix

A [Hilbert matrix](https://en.wikipedia.org/wiki/Hilbert_matrix) $ H $ has elements defined by

\begin{equation} 
H_{ij} = \frac{1}{i + j - 1}.
\end{equation} 

A $3 \times 3$ Hilbert matrix is
\begin{equation}
H = 
\begin{bmatrix}
1 & \frac{1}{2} & \frac{1}{3} \\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} \\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5}. 
\end{bmatrix}
\end{equation} 

Hilbert matrices are known to have large condition numbers. Below is an example of a $5 \times 5$ Hilbert matrix. You can use np.linalg.cond() to compute the condition number of the matrix.

### Exercise
Create a $5 \times 5$ Hilbert matrix and solve $H\mathbf{x} = \mathbf{b}$ for $\mathbf{b} = [1~ 1~ 1~ 1~ 1]^T$. 

In [65]:
from scipy.linalg import hilbert

# Create a 5x5 Hilbert matrix
H = hilbert(5)

# Create a right-hand side vector (e.g., all ones)
b = np.ones(5)

# Solve Hx = b
x = np.linalg.solve(H, b)

# Calculate condition number
cond_number = np.linalg.cond(H)

print("Hilbert matrix (5x5):\n", H)
print("\nThis is vector b:", b) 
print("\nCondition number:", cond_number)
print("\nSolution x:", x)
print("\nCheck soltuion recovers b:", H@x) 

Hilbert matrix (5x5):
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]

This is vector b: [1. 1. 1. 1. 1.]

Condition number: 476607.2502425855

Solution x: [    5.          -120.           630.         -1120.00000001
   630.        ]

Check soltuion recovers b: [1. 1. 1. 1. 1.]



Let's change the vector $\mathbf{b}$ slightly by changing the first element to 0.1. Notice how much the solution $\mathbf{x}$ changes. 

In [66]:
# Solve Hx = b
bp=np.copy(b)
bp[0] = .1
xp = np.linalg.solve(H, bp)

# Calculate condition number
cond_number = np.linalg.cond(H)

print("Hilbert matrix (5x5):\n", H)
print("\nThis is vector b:", bp) 
print("\nCondition number:", cond_number)
print("\nThe perturbed solution:", xp)
print("\nThe unperturbed solution:", x)
print("\nCheck soltuion recovers perturbed b:", H@xp) 

Hilbert matrix (5x5):
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]

This is vector b: [0.1 1.  1.  1.  1. ]

Condition number: 476607.2502425855

The perturbed solution: [ -17.5  150.  -315.   140.    63. ]

The unperturbed solution: [    5.          -120.           630.         -1120.00000001
   630.        ]

Check soltuion recovers perturbed b: [0.1 1.  1.  1.  1. ]


### Example from MathWorks, Cleve Moler, [What is a Matrix Condition Number](https://blogs.mathworks.com/cleve/2017/07/17/what-is-the-condition-number-of-a-matrix/)?

Consider 
\begin{equation} 
A = \begin{bmatrix} 4.1 & 2.8 \\ 9.7 & 6.6 \end{bmatrix}. 
\end{equation}

Take $\mathbf{b}$ to be the first column of $A$, $\mathbf{b} = [ 4.1, 9.7]^T$. Solve for $\mathbf{x}$. 
Add $.01$ to the first element of $\mathbf{b}$ and notice how the solution changes. 

Perturb $A$ slightly by,  
\begin{equation} 
dA = \begin{bmatrix} 0 & 0 \\ -0.024 & 0 
\end{bmatrix}. 
\end{equation} 
Notice how the solution for $\mathbf{x}$ changes significantly. 

In [67]:
A= np.array([[4.1, 2.8],[9.7 ,6.6]]) 
print("Condition number for A", np.linalg.cond(A))

b=A[:,0]
print("b-vector", b) 
x= np.linalg.solve(A,b)
print("Solution x:", x) 


Condition number for A 1622.9993838565106
b-vector [4.1 9.7]
Solution x: [1. 0.]


In [68]:
# perturb b 
bp = np.array([0.01, 0]) + b 
print("perturbed b-vector:\n", bp) 

xp = np.linalg.solve(A, bp) 

print("pertrubed solution for x:\n", xp ) 

perturbed b-vector:
 [4.11 9.7 ]
pertrubed solution for x:
 [0.34 0.97]


In [69]:
error_b = np.linalg.norm(bp - b)/np.linalg.norm(b)
error_x = np.linalg.norm(xp-x)/np.linalg.norm(x) 
kappa = np.linalg.cond(A) 

print("error in b-vector:\n", error_b) 
print("error in x-vector:\n", error_x) 
print("condition number times error in b-vector:\n", kappa*error_b) 


error in b-vector:
 0.000949585833500486
error in x-vector:
 1.1732433677630363
condition number times error in b-vector:
 1.5411772226901599


In [70]:
dA = np.array([[0, 0],[-.024, .008]]) 
print("dA:\n", dA)
print("A + dA:\n", A + dA) 

dA:
 [[ 0.     0.   ]
 [-0.024  0.008]]
A + dA:
 [[4.1   2.8  ]
 [9.676 6.608]]


In [71]:
# solve for x 
print("perturbed solution:\n", np.linalg.solve(A + dA, b) ) 

perturbed solution:
 [ 1.56387916e+13 -2.28996591e+13]


In [72]:
np.linalg.inv(A + dA) 

array([[-1.53781451e+15,  6.51616316e+14],
       [ 2.25179981e+15, -9.54152463e+14]])

In [73]:
np.linalg.cond(A + dA) 

8675056625322446.0

### Example from MIT Dynamics Systems and Control Course
This example is from an MIT course on [Dynamic Systems and Control, chapter 4](https://ocw.mit.edu/courses/6-241j-dynamic-systems-and-control-spring-2011/04fddfbcb1eb933ecca85dab8bfbb171_MIT6_241JS11_chap04.pdf).

Consider 
\begin{equation} 
A = \begin{bmatrix} 100 & 100 \\ 100.2 & 100 \end{bmatrix}. 
\end{equation}
What is the solution to $A \mathbf{x}= \mathbf{b}$ for $\mathbf{b} = [ 1, -1 ]^T$. What happens to the solution when you perturb $A$ by a small amount on the order of 0.1%, by 
\begin{equation} 
\Delta A = \begin{bmatrix} 0 & 0 \\ -.1 & 0 \end{bmatrix}. 
\end{equation} 

Here is the Python solution. 

In [74]:
# Matrix from example above 
A = np.array([[100, 100],[100.2, 100]]) 
A

array([[100. , 100. ],
       [100.2, 100. ]])

In [75]:
# b-vector 
b = np.array([1, -1]) 

In [76]:
# compute the inverse 
A_inv = np.linalg.inv(A) 
A_inv

array([[-5.  ,  5.  ],
       [ 5.01, -5.  ]])

In [77]:
# unperturbed solution 
x = A_inv@b 
print("The unperturbed solution is:", x)

The unperturbed solution is: [-10.    10.01]


In [78]:
# perturbation 
dA = np.array([[0, 0],[-.1, 0]]) 
A + dA

array([[100. , 100. ],
       [100.1, 100. ]])

In [79]:
# pertrubed inverse 
Ap_inv=np.linalg.inv(A + dA)
Ap_inv

array([[-10.  ,  10.  ],
       [ 10.01, -10.  ]])

In [80]:
# perturbed solution 
xp = Ap_inv@b
print("The perturbed solution is:", xp) 

The perturbed solution is: [-20.    20.01]


In [81]:
dx=x - xp 
a = np.linalg.norm(dx)/np.linalg.norm(x)
a

0.9995001250624836

In [82]:
b = np.linalg.norm(dA)/np.linalg.norm(A)
b

0.0004997499377186054

In [83]:
kappa = np.linalg.cond(A) 
kappa

2002.0015004997722

In [84]:
kappa*b

1.0005001251873158

## Matrix 2 Norm, SVD, and Condition Number

### Matrix 2-Norm

The **2-norm** (also called the **spectral norm** or **operator norm**) of a matrix measures how much a matrix can stretch a vector in Euclidean space. It is defined as the maximum singular value of the matrix, and for square matrices, it corresponds to the largest eigenvalue in absolute value. A high 2-norm means the matrix can stretch vectors significantly, whereas a low 2-norm means the matrix causes little distortion.

For a matrix $A$, the **2-norm** is given by:

\begin{equation}
||A||_2 = \max_{\mathbf{x} \neq 0} \frac{||A\mathbf{x}||_2}{||\mathbf{x}||_2}
\end{equation}

where:
- $\mathbf{x}$ is any nonzero vector,
- $||A\mathbf{x}||_2$ is the 2-norm of $A\mathbf{x}$,
- $||\mathbf{x}||_2$ is the 2-norm of $\mathbf{x}$.

Alternatively, for square matrices, the 2-norm can be computed as:

\begin{equation}
||A||_2 = \sigma_{\max}(A)
\end{equation}

where $\sigma_{\max}(A)$ is the largest singular value of $A$, which can be computed via singular value decomposition (SVD).

---

### Properties of the 2-Norm

1. **Non-negativity**: $||A||_2 \geq 0$, and $||A||_2 = 0$ if and only if $A$ is the zero matrix.
2. **Scaling**: For any scalar $k$, $||kA||_2 = |k| \, ||A||_2$.
3. **Triangle inequality**: $||A + B||_2 \leq ||A||_2 + ||B||_2$.
4. **Sub-multiplicative property**: $||AB||_2 \leq ||A||_2 ||B||_2$.

---

### Singular Values

The **SVD** (singular value decomposition) of a matrix $A$ is:

\begin{equation}
A = U \Sigma V^T,
\end{equation}

where:
- $U \in \mathbb{R}^{m \times m}$ is orthogonal ($U^T U = \mathbf{I}$),
- $\Sigma \in \mathbb{R}^{m \times n}$ is diagonal with non-negative entries,
- $V \in \mathbb{R}^{n \times n}$ is orthogonal ($V^T V = \mathbf{I}$).

The diagonal entries $\sigma_1, \sigma_2, \dots, \sigma_r$ of $\Sigma$ are called the **singular values** of $A$. Singular values describe how much $A$ stretches vectors along different directions.

- $\sigma_1 \geq \sigma_2 \geq \dots \geq \sigma_r \geq 0$,
- $\sigma_1$ = maximum stretching,
- $\sigma_r$ = minimum stretching.

---

### Matrix Condition Number from SVD

The **condition number** of $A$ (with respect to the 2-norm) is defined as:

\begin{equation}
\kappa(A) = \frac{\sigma_{\max}(A)}{\sigma_{\min}(A)}
\end{equation}

where:
- $\sigma_{\max}(A)$ = largest singular value,
- $\sigma_{\min}(A)$ = smallest nonzero singular value.

---

### Example 
Below the condition number and matrix norm for a $6 \times 6$ Hilbert matrix is computed via SVD and shown to match np.linalg.cond() and np.linalg.norm(). 

In [85]:
# 6 by 6 Hilbert matrix 
H = hilbert(6)
print("6 by 6 Hilbert matrix:\n",H)

6 by 6 Hilbert matrix:
 [[1.         0.5        0.33333333 0.25       0.2        0.16666667]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]]


In [86]:
print("Condition number from linalg.cond:",np.linalg.cond(H))

Condition number from linalg.cond: 14951058.642254734


In [87]:
print("2-norm from linalg.norm:",np.linalg.norm(H,2))

2-norm from linalg.norm: 1.6188998589243393


In [88]:
# SVD factorization
U,S,VT=np.linalg.svd(H)

In [89]:
print("Max singular value, compare to 2-norm")
np.max(S)

Max singular value, compare to 2-norm


1.6188998589243393

In [90]:
# remove any zero elements in S
idx=np.nonzero(S)
S=S[idx]
print("Ratio of maximum and minimum (smallest non-zero) singular values, compare to condition number.") 
np.max(S)/np.min(S)

Ratio of maximum and minimum (smallest non-zero) singular values, compare to condition number.


14951058.642254738

In [128]:
A = np.array([[11, 10, 14], [12, 11, -13], [14, 13, -66]]) 
b = np.array([1.001, .999, 1.001]) 

In [129]:
x = np.linalg.solve(A, b) 
x

array([-0.683,  0.843,  0.006])

In [131]:
A@x 

array([1.001, 0.999, 1.001])

In [133]:
bp = np.ones(3)
xp = np.linalg.solve(A,bp) 

In [134]:
xp 

array([ 1.00000000e+00, -1.00000000e+00, -1.66533454e-16])

In [138]:
np.linalg.norm(bp-b)/np.linalg.norm(b)*100

0.09996663337406798

In [140]:
np.linalg.norm(xp-x)/np.linalg.norm(x)*100

230.0355196923597

In [120]:
b

array([0.01, 0.01, 0.01, 0.01])