# Matrix Stability 

In [2]:
import numpy as np
from numpy.linalg import svd, cholesky

def is_positive_definite(matrix):
    try:
        cholesky(matrix)
        return True
    except np.linalg.LinAlgError:
        return False

# Example of a nearly singular positive semi-definite matrix
A_unstable = np.array([[1.0, 1.0], [1.0, 1.0 + 1e-9]])

print("Matrix A (Nearly Singular):\n", A_unstable)
print("Is A positive definite?", is_positive_definite(A_unstable))

# Attempt Cholesky decomposition
try:
    L_chol_unstable = cholesky(A_unstable)
    print("Cholesky Decomposition of A:\n", L_chol_unstable)
except np.linalg.LinAlgError as e:
    print(f"Cholesky Decomposition failed: {e}")

# Perform Singular Value Decomposition
U_unstable, S_unstable, Vh_unstable = svd(A_unstable)
print("SVD of A:")
print("U:\n", U_unstable)
print("Singular Values (S):\n", S_unstable)
print("Vh:\n", Vh_unstable)

print("\n------------------------------------\n")

# Example of a well-conditioned positive definite matrix
A_stable = np.array([[2.0, 1.0], [1.0, 2.0]])

print("Matrix B (Well-Conditioned):\n", A_stable)
print("Is B positive definite?", is_positive_definite(A_stable))

# Attempt Cholesky decomposition
L_chol_stable = cholesky(A_stable)
print("Cholesky Decomposition of B:\n", L_chol_stable)

# Perform Singular Value Decomposition
U_stable, S_stable, Vh_stable = svd(A_stable)
print("SVD of B:")
print("U:\n", U_stable)
print("Singular Values (S):\n", S_stable)
print("Vh:\n", Vh_stable)

Matrix A (Nearly Singular):
 [[1. 1.]
 [1. 1.]]
Is A positive definite? True
Cholesky Decomposition of A:
 [[1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 3.16227779e-05]]
SVD of A:
U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular Values (S):
 [2.00000000e+00 5.00000026e-10]
Vh:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

------------------------------------

Matrix B (Well-Conditioned):
 [[2. 1.]
 [1. 2.]]
Is B positive definite? True
Cholesky Decomposition of B:
 [[1.41421356 0.        ]
 [0.70710678 1.22474487]]
SVD of B:
U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular Values (S):
 [3. 1.]
Vh:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


While the provided Python code doesn't directly $\textit{prove}$ the stability mathematically, it demonstrates a scenario where Singular Value Decomposition (SVD) can handle a nearly singular positive semi-definite matrix more gracefully than the Cholesky decomposition.

**Explanation of the Code and Stability:**

1.  **Nearly Singular Matrix ($A_{\text{unstable}}$):**
    * This matrix is close to being singular because its determinant is very small (approximately $1 \times 10^{-9}$).
    * Although theoretically positive semi-definite (eigenvalues are non-negative), the Cholesky decomposition in numerical computation can fail or become unstable due to the presence of very small values on the diagonal during the decomposition process, potentially leading to division by near-zero numbers or taking the square root of a slightly negative number due to floating-point inaccuracies. The code demonstrates this potential failure.
    * SVD, on the other hand, decomposes the matrix into three other matrices ($U$, $S$, $Vh$). The singular values (the diagonal elements of $S$) reveal the near singularity by having a very small value. The process of computing SVD is generally more numerically stable for such cases.

2.  **Well-Conditioned Matrix ($A_{\text{stable}}$):**
    * This matrix is positive definite and well-conditioned (its determinant is 3).
    * Both Cholesky and SVD work well for such matrices, as demonstrated by the successful decomposition in the code.

**Why SVD is Generally More Stable than Cholesky:**

* **Applicability:** SVD can be applied to any $m \times n$ matrix (even rectangular or rank-deficient matrices), whereas Cholesky decomposition is specifically for Hermitian (symmetric for real-valued matrices) **positive definite** matrices. If a matrix is positive semi-definite (like $A_{\text{unstable}}$), Cholesky might fail or be numerically unstable.

* **Handling Near Singularity:** SVD is more robust when dealing with matrices that are close to singular. The singular values provide a direct measure of how close the matrix is to being rank-deficient. Small singular values indicate near singularity, but the decomposition itself remains well-behaved.

* **Condition Number:** The stability of solving linear systems involving a matrix is often related to its condition number (the ratio of the largest to the smallest singular value). A high condition number indicates potential instability. SVD explicitly provides the singular values, making it easier to assess the condition of the matrix. For Cholesky, the condition number of $A$ is related to the condition number of its Cholesky factor $L$ by
    \begin{equation}
    \kappa(A) = \kappa(L)^2
    \end{equation}
    which can sometimes exacerbate numerical issues if $A$ is ill-conditioned.

* **Algorithm:** The algorithms used to compute SVD (often involving iterative methods like QR iteration) are designed to be numerically stable. Cholesky decomposition, while computationally efficient, is a direct method that can be more sensitive to rounding errors, especially when the matrix is close to being singular or not strictly positive definite.

**In summary:** While Cholesky decomposition is an efficient and stable method for solving linear systems with symmetric positive definite matrices, SVD is a more generally applicable and numerically robust decomposition, particularly when dealing with potentially singular or ill-conditioned matrices. The example above illustrates a case where Cholesky struggles due to near singularity, while SVD still provides a meaningful decomposition.